name: AppScan CodeSweep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  run-appscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install AppScan CodeSweep
        run: |
          curl -sL https://github.com/AppScan/codeSweep/releases/download/vX.X.X/codeSweep-X.X.X-linux-x86_64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/codeSweep-X.X.X-linux-x86_64 /usr/local/bin/codeSweep

      - name: Run AppScan CodeSweep
        run: |
          codeSweep --project .

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
