name: AppScan CodeSweep

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  run-appscan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install AppScan CodeSweep
        run: |
          curl -sL https://github.com/AppScan/codeSweep/releases/download/vX.X.X/codeSweep-X.X.X-linux-x86_64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/codeSweep-X.X.X-linux-x86_64 /usr/local/bin/codeSweep

      - name: Check GitHub Token
        run: |
          echo "Checking GITHUB_TOKEN permissions..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/

      - name: Run AppScan CodeSweep
        run: |
          codeSweep --project . --output results.sarif

      - name: Upload SARIF Report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
